a=int(input())
if a==1: print("Roșu")
elif a==2: print("Oranj")
elif a==3: print("Galben")
elif a==4: print("Verde")
elif a==5: print("Albastru")
elif a==6: print("Indigou")
elif a==7: print("Violet")
else: print("Învață culorile")
