a=int(input('Dati un numar - '))
if a==1: print("Roșu")
elif a==2: print("Oranj")
elif a==3: print("Galben")
elif a==4: print("Verde")
elif a==5: print("Albastru")
elif a==6: print("Indigou")
elif a==7: print("Violet")
else: print("Învață culorile")
a=int(input('Nr de fete din tabără - '))
print(a*2+10,"elevi")
a=int(input('Nr de copii la prima stație - '))
b=int(input('Nr de copii la a doua stație - '))
print("Au plecat",a+b+7,"copii în excursie")
a=int(input('Nr de globulețe albe - '))
print(4*a+4,"globulețe pe brad")
a=int(input('Nr pentru joc - '))
print(a-2,a-1,a,a+1,a+2)
a=int(input('Nr de mere - '))
print("Primul are",a-2,"mere, iar al doilea are",a+1,"mere")
v=int(input('Vârsta copilului - '))
print("greutate=",2*v+8,"kg, înălțime=",5*v+80,"cm")
a=int(input('Prima variantă de comb. I Nr de combinație - '))
b=int(input('II Nr de combinație - '))
c=int(input('III Nr de combinație - '))
print(a*100+c*10+b,a*100+b*10+c,c*100+b*10+a,c*100+a*10+b,b*100+a*10+c)
print(a*100+b*10+c,a*100+c*10+b,b*100+a*10+c,b*100+c*10+a,c*100+a*10+b,c*100+b*10+a)
a=int(input('I termen - '))
b=int(input('II termen - '))
c=int(input('III termen - '))
print(a,"+",b,"=",a+b)
print(a,"+",c,"=",a+c)
print(b,"+",c,"=",b+c)
n=int(input('Nr pentru tabla înmulțirii - '))
for x in range(1, 11):
 print(n,"*",x,"=",n*x)
a=int(input('Iepuri la început de lună - '))
b=int(input('Iepuri morți:( - '))
c=int(input('Iepuri născuți:) - '))
print(a-b+c,"iepuri")
a=int(input('I Nr de ouă - '))
b=int(input('II Nr de ouă - '))
c=int(input('III Nr de ouă - '))
d=int(input('IV Nr de ouă - '))
print((a+b+c+d)*7,"ouă săptămânal")
